dist: trusty
sudo: false
matrix:
  include:
  - language: objective-c
    osx_image: xcode12.2
    before_install:
    - date
    - export TZ=America/New_York
    - date
    before_script:
    - echo ${TZ}
    script:
    - pwd
    - ls -ltra
    - xcrun instruments -s devices
    - xcodebuild clean test -project iOSurl.xcodeproj -scheme iOSurl -destination "platform=iOS Simulator,name=iPhone X" -quiet
    after_success:
    - bash <(curl -s https://codecov.io/bash)
 







